development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Tullos Sexton Cookbook
  admin_email: csexton@gmail.com
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Bort
  admin_email: bort@bort.com  
  
production:
  site_url: http://cookbook.fuzzymonk.com
  site_name: Tullos Sexton Cookbook
  admin_email: csexton@gmail.com

