development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Tullos Sexton Cookbook
  admin_email: csexton@gmail.com
  
test:
  <<: *non_production_settings
  
production:
  site_url: http://cookbook.fuzzymonk.com
  site_name: Tullos Sexton Cookbook
  admin_email: csexton@gmail.com

